### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by marko89kv** [LynxITDigital/react-native-contacts-wrapper#7]
Hi, I have installed the module, did rnpm link, everything good, but now my project cannot be compiled:

```
react-native-contacts-wrapper/android/app/src/main/java/com/lynxit/contactswrapper/ContactsWrapper.java:31: error: ContactsWrapper is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class ContactsWrapper extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
```

and

```
react-native-contacts-wrapper/android/app/src/main/java/com/lynxit/contactswrapper/ContactsWrapper.java:80: error: method does not override or implement a method from a supertype
    @Override
    ^
```

**Comment by marko89kv** [comment]
Fixed with choosing `com.facebook.react:react-native:0.20.1` as a dependency, original was
`com.facebook.react:react-native:+`, so now it compiles, I'll write here in a minute if it works, also :)

**Comment by marko89kv** [comment]
It crashes when I select a contact:

```
java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
                                                                          at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:210)
                                                                          at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:612)
                                                                          at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
                                                                          at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
                                                                          at android.app.Activity.dispatchActivityResult(Activity.java:6135)
                                                                          at android.app.ActivityThread.deliverResults(ActivityThread.java:3535)
                                                                          at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582)
                                                                          at android.app.ActivityThread.access$1300(ActivityThread.java:144)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by JaxGit** [comment]
Please take a look at the latest readme and see if you could fix it. 
Take manual steps instead of automatic linking using rnpm as Android project template has been changed since RN 0.29. 
And the abstract method error had been fixed since 0.1.3.

**Comment by deepmehtait** [comment]
@JaxGit : I am also having same issue.
<img width="837" alt="screen shot 2016-09-20 at 8 12 31 pm" src="https://cloud.githubusercontent.com/assets/8682058/18696667/c7217c82-7f6f-11e6-80ca-777ad25d3e1b.png">

<img width="306" alt="screen shot 2016-09-20 at 8 19 21 pm" src="https://cloud.githubusercontent.com/assets/8682058/18696642/a14610fe-7f6f-11e6-8b58-cebf3803e2fd.png"> 
manually used 0.1.3 

`npm install react-native-contacts-wrapper --save` installed 0.3.2 version.

**Comment by marko89kv** [comment]
So, how do I actually install it? When I did `npm install react-native-contacts-wrapper --save`, it installed version 0.2.1

**Comment by marko89kv** [comment]
Also, I did the manual steps of linking the Android project

**Comment by deepmehtait** [comment]
@marklynx I also noticed that when you open Android project of contact wrapper it wont show any errors which it is showing once library is getting integrated into project.

**Comment by Proyoyo** [comment]
@marko89kv version 0.2.1 behaves the same as v0.1.3. Everything that @JaxGit mentioned above is still applicable
